theme: minima
title:
author:
description:

url: "https://example.com" # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  
  plugins:
  - jekyll-feed

algolia:
  application_id: W0NSNG1DC8
