project:
  type: website
  output-dir: docs

website:
  site-url: "https://joshua-larsen.github.io/"
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joshua-larsen
      - icon: twitter
        href: https://twitter.com/_joshualarsen
      - icon: linkedin
        href: https://linkedin.com/in/joshua-larsen-salesforce
      - icon: stack-overflow
        href: https://stackoverflow.com/users/21593536/joshua-l?tab=profile
      - icon: code-wars
        href: www.codewars.com/r/sdr0pQ
      - icon: rss
        href: https://joshua-larsen.github.io/blog/feed.xml
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto

listing:
  contents: posts
  feed: true


