project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/joshua-larsen
      - icon: twitter
        href: https://twitter.com/_joshualarsen
      - icon: linkedin
        href: https://linkedin.com/in/joshua-larsen-salesforce
      - icon: stack-overflow
        href: https://stackoverflow.com/users/21593536/joshua-l?tab=profile
format:
  html:
    theme: cosmo
    css: styles.css



